function Hd = baselineWanderButt
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 30-Nov-2017 20:43:28

N    = 10;   % Order
F3dB = 0.5;  % 3-dB Frequency
Fs   = 200;  % Sampling Frequency

h = fdesign.highpass('n,f3db', N, F3dB, Fs);

Hd = design(h, 'butter', ...
    'SystemObject', true);


