function Hd = baselineWanderHamm
%BASELINEWANDERHAMM Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 01-Dec-2017 15:20:53

% FIR Window Highpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 100;  % Sampling Frequency

N    = 400;      % Order
Fc   = 0.5;      % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'high', win, flag);
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
